itemOptions:
  lock-item-name: "&rЗамок"
  key-item-name: "&rКлюч"
  creator-line: "создал - {nick}"

message:
  lock-setup: "Замок установлен с {id}"
  key-setup: "Ключ привязан к {id}"
  chest-closed: "Хранилище закрыто, возьмите нужный ключ."

options:
  can-open-unregister-chest: true


