itemOptions:
  key-item: PAPER
  lock-item: PAPER
  id-formate: dd-M-yyyy-id
  id-line: "номер - {id}"
  creator-line: "создал - {nick}"

message:
  lock-settup: "Замок установлен с {id}"
  key-settup: "Ключ привязан к {id}"

options:
  can-open-unregister-chest: false
  chest-creator-can-register-many-keys: false

