itemOptions:
  lock-item-name: "Замок"
  key-items-names:
    - "Золотой ключ"
    - "Железный ключ"
    - "Медный ключ"
  id-in-lore: "#F77000{id}"
  original-lore: "#FFD29DХозяин - #F77000{player} #FFD29D| #F77000Оригинал"
  copy-lore: "#FFD29DХозяин - #F77000{player} #FFD29D| #F77000Копия"

crowbarFeature:
  crowbar-item-name: "Монтировка"
  sound: ---
  sound-volume: 50
  sound-pitch: 50
  chance: 25
  message-enabled: true

message:
  lock-setup: "#A5D856Замок установлен с #F2E9E4{id} #A5D856id"
  key-setup: "#A5D856Ключ привязан к #F2E9E4{id} #A5D856id"
  chest-closed: "#ED4343Хранилище закрыто, возьмите нужный ключ."
  key-already-bound: "#ED4343Ключ уже привязан"
  lock-already-bound: "#ED4343Замок уже привязан"
  need-bind-key: "#ED4343Нужно привязать ключ"
  crowbar-succes: "#A5D856Удалось сломать хранилище"
  crowbar-fail: "#ED4343Не удалось сломать хранилище"



