itemOptions:
  lock-item-name: "&rЗамок"
  key-item-name: "&rКлюч"
  id-formate: dd-M-yyyy-id
  creator-line: "создал - {nick}"

message:
  lock-setup: "Замок установлен с {id}"
  key-setup: "Ключ привязан к {id}"
  chest-closed: "Сундук закрыт"

options:
  can-open-unregister-chest: false
  chest-creator-can-register-many-keys: false

