itemOptions:
  lock-item-name: "Замок"
  key-item-name: "Золотой ключ"
  creator-line: "создал - {nick}"

message:
  lock-setup: "Замок установлен с {id}"
  key-setup: "Ключ привязан к {id}"
  chest-closed: "Хранилище закрыто, возьмите нужный ключ."
  key-already-bound: "Ключ уже привязан"
  lock-already-bound: "Замок уже привязан"

options:
  can-open-unregister-chest: true


